---
# handlers file for dashy
  - name: Restart {{ dashy_container_name }} container
    systemd:
      state: restarted
      enabled: yes
      daemon_reload: yes
      name: "{{ dashy_container_name }}"
