---
# tasks file for npm
  - name: Creates npm directory
    file:
      path: "{{item }}"
      state: directory
    loop:
      - "{{docker_folder}}/{{npm_container_name}}"

  - name: Generate npm docker_compose
    template:
      src: "docker_compose.j2"
      dest: "{{docker_folder}}/{{npm_container_name}}/docker-compose.yml"
    notify: Restart {{npm_container_name}} container

  - name: Generate npm init
    template:
      src: "docker_compose_service.j2"
      dest: "/etc/systemd/system/{{npm_container_name}}.service"
    notify: Restart {{npm_container_name}} container
