---
# handlers file for blackbox_exporter
  - name: Restart {{ blackbox_exporter_container_name }} container
    systemd:
      state: restarted
      enabled: yes
      daemon_reload: yes
      name: "{{ blackbox_exporter_container_name }}"
