---
# tasks file for dwordpress
  - name: Creates dwordpress directory
    file:
      path: "{{ item }}"
      state: directory
    loop:
      - "{{docker_folder}}/{{dwordpress_container_name}}"

  - name: Generate dwordpress docker_compose
    template:
      src: "docker_compose.j2"
      dest: "{{docker_folder}}/{{dwordpress_container_name}}/docker-compose.yml"
    notify: Restart {{dwordpress_container_name}} container

  - name: Generate dwordpress init
    template:
      src: "docker_compose_service.j2"
      dest: "/etc/systemd/system/{{dwordpress_container_name}}.service"
    notify: Restart {{dwordpress_container_name}} container
