---
# tasks file for node_exporter
- name: Copy the node_exporter systemd service file
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/{{node_exporter_service_name}}.service
    owner: root
    group: root
    mode: 0644
  notify: Restart Node Exporter
