---
# tasks file for prometheus
- name: Copy the prometheus systemd service file
  template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/{{prometheus_service_name}}.service
    owner: root
    group: root
    mode: 0644
  notify: Restart Prometheus

- name: Clone a private repository into {{PROJECT_NAME}} folder.
  git:
    repo: "{{ prometheus_config_git_repo }}"
    version: "{{ prometheus_config_git_branch }}"
    dest: "/tmp/prom_config"
    accept_hostkey: yes
  become: no
  delegate_to: localhost

- name: Propagate prometheus config folder
  copy:
    src: "/tmp/prom_config/"
    dest: "{{prometheus_folder}}/config/"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_user }}"
  notify: Restart Prometheus
