---
- name: Install, configure, and start Apache
  block:

  - name: Add an Apt signing key
    apt_key:
      url: "{{ item }}"
      state: present
    loop:
      - "https://packages.grafana.com/gpg.key"

  - name: Add repositorys
    apt_repository:
      repo: "{{ item }}"
    loop:
      - "deb https://packages.grafana.com/oss/deb stable main"
    ignore_errors: yes

  - name: Update apt-get repo and cache
    apt:
      update_cache: yes
      force_apt_get: yes
      cache_valid_time: 3600

  - name: Install useful packages
    apt:
      update_cache: yes
      cache_valid_time: 3600
      name:
        - grafana
      state: latest

  when: ansible_os_family == "Debian"
