---

  - name: Add prometheus user
    user:
      name: "{{ prometheus_user }}"
      append: "yes"
      shell: "/sbin/nologin"
      state: "present"
      createhome: "no"

  - name: Creates directory
    file:
      path: "{{item }}"
      owner: "{{ prometheus_user }}"
      group: "{{ prometheus_user }}"
      state: directory
    loop:
      - "{{prometheus_folder}}"
      - "{{prometheus_storage_tsdb_path}}"

  - name: Download prometheus binary to local folder
    become: false
    get_url:
      url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_latest_releases }}/prometheus-{{ prometheus_latest_releases }}.linux-{{ arch }}.tar.gz"
      dest: "/tmp/prometheus-{{ prometheus_latest_releases }}.linux-{{ arch }}.tar.gz"
      mode: '0644'
    register: _download_binary
    until: _download_binary is succeeded
    retries: 5
    delay: 2
    delegate_to: localhost
    check_mode: false

  - name: Unpack prometheus binary
    become: false
    unarchive:
      src: "/tmp/prometheus-{{ prometheus_latest_releases }}.linux-{{ arch }}.tar.gz"
      dest: "/tmp"
      creates: "/tmp/prometheus-{{ prometheus_latest_releases }}.linux-{{ arch }}/prometheus"
    delegate_to: localhost
    check_mode: false

  - name: Propagate prometheus binaries
    copy:
      src: "/tmp/prometheus-{{ prometheus_latest_releases }}.linux-{{ arch }}/{{ item }}"
      dest: "{{ prometheus_folder }}/{{ item }}"
      mode: 0755
      owner: "{{ prometheus_user }}"
      group: "{{ prometheus_user }}"
    notify: Restart Prometheus
    loop:
      - prometheus
      - promtool

  - name: Propagate prometheus folder
    copy:
      src: "/tmp/prometheus-{{ prometheus_latest_releases }}.linux-{{ arch }}/{{ item }}"
      dest: "{{ prometheus_folder }}/{{ item }}"
      owner: "{{ prometheus_user }}"
      group: "{{ prometheus_user }}"
    notify: Restart Prometheus
    loop:
      - consoles
      - console_libraries
