---
# handlers file for node_exporter
    - name: Restart Prometheus
      systemd:
        state: restarted
        enabled: yes
        daemon_reload: yes
        name: "{{ prometheus_service_name }}"

    - name: Restart Grafana
      systemd:
        state: restarted
        enabled: yes
        daemon_reload: yes
        name: "grafana-server"
