---
# handlers file for prometheus
  - name: Restart {{ prometheus_container_name }} container
    command: |
      docker compose down
    args:
      chdir: "{{docker_folder}}/{{prometheus_container_name}}/"
    notify: UP {{ prometheus_container_name }} container

  - name: UP {{ prometheus_container_name }} container
    command: |
      docker compose up -d --quiet-pull --force-recreate
    args:
      chdir: "{{docker_folder}}/{{prometheus_container_name}}/"