---
# handlers file for MinecraftServer
  - name: Restart {{ MinecraftServer_container_name }} container
    systemd:
      state: restarted
      enabled: yes
      daemon_reload: yes
      name: "{{ MinecraftServer_container_name }}"
