---
# tasks file for dockerTMP
  - name: Creates dockerTMP directory
    file:
      path: "{{item }}"
      state: directory
    loop:
      - "{{docker_folder}}/{{dockerTMP_container_name}}"

  - name: Generate dockerTMP docker_compose
    template:
      src: "docker_compose.j2"
      dest: "{{docker_folder}}/{{dockerTMP_container_name}}/docker-compose.yml"
    notify: Restart {{dockerTMP_container_name}} container

  - name: Generate dockerTMP init
    template:
      src: "docker_compose_service.j2"
      dest: "/etc/systemd/system/{{dockerTMP_container_name}}.service"
    notify: Restart {{dockerTMP_container_name}} container
