---
# handlers file for npm
  - name: Restart {{ npm_container_name }} container
    systemd:
      state: restarted
      enabled: yes
      daemon_reload: yes
      name: "{{ npm_container_name }}"
