---
# tasks file for linux-update
    - name: Update apt repo and cache on all Debian/Ubuntu boxes
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Upgrade all packages on servers
      apt: upgrade=dist force_apt_get=yes

#    - name: Check if a reboot is needed on all servers
#      register: reboot_required_file
#      stat: path=/var/run/reboot-required get_md5=no

#    - name: Reboot the box if kernel updated
#      debug:
#        msg: "Reboot required by Ansible for kernel updates"
#      when: reboot_required_file.stat.exists
