---
# tasks file for linux-update
  - name: setup
    setup:
      
  - name: Dependonsi Debian
    include_tasks: "debian.yml"
    when: ansible_os_family == "Debian"

  - name: Dependonsi RedHat
    include_tasks: "redhat.yml"
    when: ansible_os_family == "RedHat" or ansible_os_family == "Rocky"
