---
# tasks file for RPstore
- name: Install useful packages
  apt:
    name:
    - hd-idle
    state: latest

- name: SSHD
  lineinfile:
    dest: /etc/default/hd-idle
    state: present
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - { regexp: '^START_HD_IDLE=', line: 'START_HD_IDLE=true' }
    - { regexp: '^HD_IDLE_OPTS=', line: 'HD_IDLE_OPTS="-i 1200 -l /var/log/hd-idle.log"' }
  notify: Restart hd-idle

- name: Remove udisks2
  apt:
    name:
    - udisks2
    state: absent

- name: Stop and disable services
  service:
    name: "{{ item }}"
    enabled: no
    state:   stopped
  loop:
    - "smartmontools.service"
    - "fstrim.timer"
    - "e2scrub_all.timer"

- name: Dependonsi Debian
  include: "smb.yml"
