---
# tasks file for AnsibleWIREGUARD
  - name: Install wireguard
    apt:
      name: wireguard

  - name: Copy systermd
    copy:
      src: "{{item}}"
      dest: "/etc/systemd/system/"
    loop:
      - "wgui.service"
      - "wgui.path"
    notify: Restart wireguard

  - name: Create directorys
    file:
      path: "{{item }}"
      state: directory
    loop:
      - "{{docker_folder}}/{{wggui_container_name}}"
      - "{{docker_folder}}/{{wggui_container_name}}/db"

  - name: Generate docker_compose
    template:
      src: "docker_compose.j2"
      dest: "{{docker_folder}}/{{wggui_container_name}}/docker-compose.yml"
    notify: Restart {{wggui_container_name}} container

  - name: Generate init
    template:
      src: "docker_compose_service.j2"
      dest: "/etc/systemd/system/{{wggui_container_name}}.service"
    notify: Restart {{wggui_container_name}} container
